<x-guest-layout>
<h1>People of Monsters Masters & Mobsters</h1>


<h2>
<figure class="figure float-end">
<img src="https://images.leadconnectorhq.com/image/f_webp/q_80/r_320/u_https://storage.googleapis.com/msgsndr/3vVAHmly2NuweaJs74jQ/media/666cf66a375173b5afd89198.jpeg" alt="FAQ image" class="figure-img img-fluid rounded" loading="lazy" alt="Jay Bienvenu">
<figcaption class="figure-caption text-center">Jay Bienvenu</figcaption>
</figure>
Jay Bienvenu<br/><small>Creator, Curator and Canonist</small></h2>

<p>Monsters Masters &amp; Mobsters is created and developed by Jay Bienvenu. Jay was born in Lafayette, Louisiana, and has lived in Louisiana for most of his life but also spent two winters in Wisconsin. He completed high school at the Louisiana School for Math, Science and Arts and earned two degrees in engineering from the University of Louisiana at Lafayette. His day job is software developer for a boutique Internet and Web services company. He currently lives in Ponchatoula, Louisiana. He has three children.</p>

<h1>Credits and Acknowledgements</h1>

<p><strong>Bernadette Bienvenu</strong> Design input, proofreading, emotional support, occasional food.</p>

   

<p>We use icons from <a href="https://game-icons.net/">Game-Icons.net</a> and <a href="https://thenounproject.com/">The Noun Project</a>. Icons are used under a Creative Commons license. <!--The icons are used in the following ways:--></p>

<p>Some patterns generated by <a href="https://pattern.monster/">Pattern Monster</a>.</p>

<h2><a href="/cards">Card System</a></h2>

<ul class="list-unstyled">
<li><strong><a href="/people/msb">Merry Shuporna Biswas</a></strong> Card art.</li>
<li><strong>Nilanjan Malakar</strong> Card art.</li>
<li><strong>Eric Martin</strong> Card art.</li>
</ul>

<h2><a href="/cg">{{__('cg')}}</a></h2>

<ul class="list-unstyled">
<li><strong>Hunter Andries</strong> Playtesting.</li>
<li><strong>Josh Bellagh</strong> Playtesting and emotional support.</li>
<li><strong>Bernadette Bienvenu</strong> Playtesting, review and editing of rules.</li>
<li><strong>Ricky Bienvenu</strong> Playtesting.</li>
<li><strong>Evan Frioux</strong> Playtesting.</li>
<li><strong>Suzette Groh</strong> Playtesting.</li>
<li><strong>Timothy Groh</strong> Playtesting.</li>
<li><strong>Ryan Kazemi</strong> Playtesting.</li>
<li><strong>Jeremy Monts</strong> Playtesting.</li>
<li><strong>Bob Whitely</strong> Review and editing of the rules.</li>
</ul>

<p><strong>Gen Con 2024 First Exposure Playtest Hall:</strong> Ray, Jacob, Karl, Sutton, Derrick, Evelyn, Corrie and Jeremy.</p>




</x-guest-layout>
