<x-guest-layout><x-slot:page-title>Lore</x-slot><h1>The New Commissioner</h1>

<p>"Congratulations, boss. Or should I call you 'commissioner'?"</p>
<p>Amalica Switch turned and gave her subordinate a half-wink. "You can call me both."</p>
<p>"How does it feel to have achieved the goal that's driven your whole career? To become the most powerful anthrope in monster sports?"</p>
<p>"We'll pop the champagne tonight. Focus on business right now. The media room is clean, right?"</p>
<p>"Of course. Checked everyone against your guest list. We stopped this one guy in the ground-floor lobby. Thought he was getting in with his old media credentials. Started blabbering about corrupt­ion and conspiracy. Security got him out of the building before he could taint anyone. We notified his now-former employer of his behavior."</p>
<p>"Good."</p>
<p>"Good thing the county and the city pay their law enforcement so poorly. And the voters keep voting down the tax increases needed to pay them. Private security firms are booming. The best people in town are on our payroll. Any questions you're expecting?"</p>
<p>"The usual discussion bait. Someone will ask us about Waxwood's daughter. And someone will remind us about Ben Livingwater. You know the media. Sell papers and generate clicks."</p>
<p>"Yeah, the Livingwater thing won't ever die, will it."</p>
<p>"Well, when you ban a two-time Diamond Champion for ethics violations, some anthropes will defend him to his death."</p>
<p>Switch and her underling arrived at the staging room adjacent to the media room. Chuck that old couch, she noted. She just leaned against the wall separating her from the media. The underling fell in line with her along the wall.</p>
<p>The media room was already awash in reporters and camera crews. Chatter permeated the wall. Switch closed her eyes and planned her entrance: her first steps on the plush merlot carpet with its swirls of color; the roar of the crowd; clicks and flashes of light; wanting to take her place at the polished oaken podium, but first taking photographs with Boris Waxwood, the outgoing commissioner.</p>
<p>The subordinate spoke. "Anything in particular on your mind?"</p>
<p>Lots of things, actually. But only so many he can work on.</p>
<p>"The backdrop in the media room. Get rid of it."</p>
<p>"The giant logo with the protruding horns, right? The one that gives Waxwood monster horns in every picture?"</p>
<p>"Exactly. Not the image I want for this job."</p>
<p>"Gotcha. Any thoughts on a replacement?"</p>
<p>"Staggered logos. Keep it simple."</p>
<p>"Alright. I'll get a design to you this week. We can get the new one printed and installed once the season ends."</p>
<p>"Thank you. My goodness, will Waxwood ever stop talking?"</p>
<p>"Well, he does have three decades of service that he has to regale for everyone."</p>
<p>"He wants to sound like he witnessed the Five Centuries of War from the front lines. And wants everyone besides his few remaining fans to remember it. Please tell me he dressed up for this."</p>
<p>"Sorry." The subordinate chuckled. "He's in that same old outfit."</p>
<p>"Someone get him to a tailor. Nobody wants to see his shoulders straining his brown tweed sports coat, or his round belly testing the weave of his vest."</p>
<p>The subordinate laughed. "True. Completely true."</p>
<p>"And get him to a barber while you're at it. Feeling old doesn't mean needing to look like it."</p>
<p>The subordinate laughed again. "Yes ma'am."</p>
<p>"Do they sell aftershave at the barbers? You can smell his brand from the suburbs. How does that slogan go again… 'for only the most mature professional'?"</p>
<p>"So mature they're practically dead."</p>
<p>This time Switched laughed. "Where is he in this speech?"</p>
<p>"Thanking his family and various employees by name"</p>
<p>"I'm not surprised. These reporters must be agonizing having to sit patiently through all this."</p>
<p>"You did select them yourself, after all. They're here for you."</p>
<p>"Exactly. Hold on… I think he's finished."</p>
<p>Through the wall, they heard their cue: "And now, the moment of the hour. Today the Executive Committee of the Monster Sports Federation selected my replacement. With great pleasure I now introduce the next commissioner of the Monster Sports Federation: Amalica Switch. She will take the helm next term, for the 127th season of monster competition. Ms. Switch, please join us."</p>
<p>Switch opened the door and stepped into her moment. Just as she expected, the room erupted.</p>
<p><hr></p>
<p>Once the photography subsided, Waxwood returned to the podium, his smile stretching the width of his long, graying beard.</p>
<p>"Ms. Switch is the perfect anthrope to take the Monster Sports Federation forward. She brings four decades of experience throughout the industry of monster sports and training. Under her leadership, the Oberforce Group launched their monster sports division. She served the local clubs of Liberty and Kingston. Most notably, she served as the first CEO of the club in Estevan. Under her leadership, the Federation brokered extended deals with our largest sponsors. The Federation's business operations are more efficient and profitable than ever. With these improvements, the Monster Sports Federation plans to improve and expand our operations both within the nation of Pluralis and throughout the world."</p>
<p>Waxwood took a breath then continued. "Our relationships with our corporate and media partners are also stronger thanks to Ms. Switch. These partners have been part of the Monster Sports Federation family for many years. We are excited to keep these relationships going. With no further ado, let's give a warm welcome to our new commissioner."</p>
<p>The audience applauded with vigor as Switch took the podium. Waxwood shuffled awkwardly to trade places with her. Switch gave the audience about a minute to adulate her, then began the acceptance speech she had memorized.</p>
<p>"Thank you, Mr. Waxwood. I want to recognize and thank the wonderful people who have joined me on this journey over the years. Thank you to my colleagues in Liberty Monster Sports Club, Kingston Monster Sports Club and Estevan Monster Sports Club. I also want to acknowledge Mullox Oberforce and the opportunity he gave me with his organization. I extend my gratitude to my mother and father, to my fellow alumni of the Caravel School of Business, and to Secretary Quiss, Treasurer Tenemos and Trustee Mackway for their support. The Monster Sports Federation is the undisputed champion of monster training and competition. Under my leadership as commissioner, we will continue the Federation's tradition of excellence."</p>
<p>"I will now take questions from the media." She pointed to a random reporter. She didn't care who it is or what they were about to ask. Nothing would stump her today.</p>
<p>"Ms. Switch, according to the most recent State of the Federation report, the business operations of the Federation are now 'more efficient.' The report listed cuts for several 'non-essential' positions, both in the Federation's central operations and at several clubs. Since the Federation operates as a not-for-profit company, does this mean the Federation will not create more jobs in the foreseeable future?"</p>
<p>Switch smiled. Exactly the sort of question she wanted to start with. Time to assert her command over the affairs of the Federation.</p>
<p>"There will always be plenty of career opportunities in the Federation and our affiliates. We employ hundreds of monster trainers who don't compete but work with the Champion and Elite Trainers. We employ nutritionists, doctors, researchers and other essential roles. Our facilities create thousands of full- and part-time jobs. And our events provide opportunities for hundreds of vendors. Altogether, the Monster Sports Federation creates tens of thousands of jobs across Pluralis. These jobs pay well and give our employees access to the same world-class healthcare and retirement plans that we offer to our stars on the field. And when a major business magazine surveyed employee pride in 100 top companies, we made the top 10. We don't have to prove ourselves; the proof is in our record, and we're proud of that record."</p>
<p>Another reporter asked, "At least one affiliate club told us they plan to reduce their charitable contributions and community involvement over the next year. Are you aware of this action? Do you plan to respond?"</p>
<p>"Local clubs make those decisions. The Monster Sports Federation and its affiliate clubs have a long history of charity. Few organizations do as much in our communities as our clubs do. We intend to continue that legacy."</p>
<p>A reporter from a back row asked, "During Mr. Waxwood's tenure, his daughter Veronica retired from professional competition and took a leadership position in the activism group Viridis. In her recent interview with SportsOne, Ms. Waxwood alleged her father allowed the Federation to become more 'materialistic.' She criticized him for divorcing the league from the 'traditions' of monster training. Ms. Switch, what is your response to Ms. Waxwood and her allegations?"</p>
<p>Waxwood frowned. His precious daughter had abandoned a Champion Trainer career. And for what? To join a radical independent group and criticize the Monster Sports Federation. He folded his arms across his chest and stared at the floor. His eyes twitched and burned.</p>
<p>Switch chose to rescue him. "The independents are free to organize and operate as they wish. Ms. Waxwood sets her own career path. She has chosen to remove the Monster Sports Federation from her career path. The Federation gives trainers an unmatched opportunity to build their careers in monster training and competition. Our analysis shows a substantial majority of top monster trainers want to work and compete for our clubs. Our recruiting programs at the top universities and academies help trainers develop their path to our organization. Surveys of champion trainers and teams from those schools are overwhelmingly in our favor: Our top collegiate trainers want to join the Monster Sports Federation. Shade from a few prominent critics won't change that."</p>
<p>Waxwood released his grip on himself and exhaled. Switch smiled again. They're eating this up.</p>
<p>Another reporter asked, "Ms. Switch, you investigated Ben Livingwater as a member of the Special Committee on Ethics. You had worked in Kingston, and you brought the ethics violations of that club to the attention of the league. Some pundits suggest the Special Committee targeted Livingwater to take the fall for other people's actions in Kingston. How do you respond to this talk?"</p>
<p>Bingo. I'm too good at reading the room.</p>
<p>"We investigated Kingston from top to bottom. We pulled a mountain of evidence out of that club. That evidence is clear: Mr. Livingwater bears full responsibility for those violations. He had full knowledge of the violations. He had opportunities to address them. And he failed to take action. Some will continue to defend Livingwater and refuse to acknowledge the evidence. They have the right to speculate, but their speculation does nothing to change the facts or move us forward."</p>
<p>"Let's look at it this way: In response to Kingston, we strengthened the Office of Compliance and Ethics. We identified unethical practices and took swift and decisive action to stop them. Both the Chamber of Commerce and the Pluralis Association for Ethics in Business have commended us. President Dycaster himself cited us as a 'model of ethics all business in Pluralis can follow.' Let's talk about our accomplishments. Let's talk about the future, rather than the past." Switch pointed to a tall woman with thick glasses. "Mary, I understand you have a question about fantasy sports."</p>
<p>The young lady rose. "Yes, commissioner. As we know you had a role in taking down the Meta-League. In the years since, the Monster Sports Federation has struggled to rebuild its fantasy sports business back to where it was before the closure of the Meta-League. Mr. Waxwood told us that he wasn't qualified to bring the Federation back into massive fantasy sports and said the next commissioner would bring fresh energy to the effort. As that new commissioner, what are your plans for fantasy sports?"</p>
<p>Switch smiled again. "The Meta-League taught us that this country wants fantasy sports. Fantasy sports gives us access to a market that we wouldn't have without it. You can expect several new fantasy sports products from us over the next few years."</p>
<p>Mary asked, "Isn't it true that nobody was ever arrested or prosecuted for the Meta-League breach?"</p>
<p>"Yes, but we aren't worried about that. We're in the business of battling monsters, not hackers." The crowd laughed.</p>
<p>A woman in a middle row asked, “Ms. Switch, your promotion to commissioner and becoming the first woman in Pluralis to lead a major-league sports operation will be an inspiration to women everywhere. What secrets of your success would you like to share with the women who are watching you today?</p>
<p>Switch replied, "The secret of my success isn't that complicated. I'm always looking for the best people to add to my organization. When I find those people, I invite them to join my organization. And if they refuse, sucks to be them." The audience laughed. “Seriously, as I mentioned earlier, I don’t just hire the best people; I make sure to treat them well as my employees. I make sure that I’m not directly giving them a reason to do a poor job or consider leaving to work elsewhere. I will be honored to serve as a role model for the young women of Pluralis.”</p>
<p>Switch and Waxwood took questions for several more minutes. Her confidence rose as she answered each question, no matter the subject, with clarity and authority. And her audience offered little resistance. Everyone ate what she served. Just as she trained them to do.</p>

</x-guest-layout>
